version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /cdktf
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /cdk
    schedule:
      interval: weekly