#!/usr/bin/env bash
set -eo pipefail

base=$(cd "$(dirname "$0")" && pwd)
s3_base="s3://${S3_CONTENT_BUCKET}"

for dir in content public; do
  aws s3 sync "${s3_base}/${dir}" \
    "${base}/../app/${dir}"
done
