#!/usr/bin/env bash
set -eo pipefail

base=$(cd "$(dirname "$0")" && pwd)
outputs_path="${base}/../cdk/outputs.json"
s3_base="s3://$(jq -r '.S3.ContentName' "${outputs_path}")"
for dir in content public; do
  aws s3 sync "${s3_base}/${dir}" \
    "${base}/../app/${dir}"
done
